# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: TechChallengeFase2 - .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup do .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
        
    - name: Restore dependencies
      run: dotnet restore src/WebApi/Fiap.TechChallenge.Fase1.WebAPI/Fiap.TechChallenge.Fase1.WebAPI.sln
      
    - name: Build projeto
      run: dotnet build --no-restore src/WebApi/Fiap.TechChallenge.Fase1.WebAPI/Fiap.TechChallenge.Fase1.WebAPI.sln
      
    - name: Teste projeto
      run: dotnet test --no-build --verbosity normal src/WebApi/Fiap.TechChallenge.Fase1.WebAPI/Fiap.TechChallenge.Fase1.WebAPI.sln
      
    - name: Saída Texto
      run: echo "Build e testes finalizados para a validação do Tech Challenge Fase 2"
